name: karim_taha_task
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.0
  equatable: ^2.0.5
  json_serializable: ^6.9.0
  cupertino_icons: ^1.0.8
  syncfusion_flutter_charts: ^20.1.55
  mocktail: ^1.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.5

flutter:
  uses-material-design: true
  assets:
    - assets/orders.json
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Medium.ttf